import "./globals.css";

import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import Provider from "@/components/providers/Provider";

const montserrat = Montserrat({
    subsets: ["latin"],
    variable: "--font-montserrat",
});

export const metadata: Metadata = {
    title: "Dolicious",
    description: "Generated by create next app",
};

const RootLayout = async ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html
            lang="en"
            className={`${montserrat.variable} h-full antialiased`}
            suppressHydrationWarning
        >
            <body className="min-h-full flex flex-col">
                <Provider>{children}</Provider>
            </body>
        </html>
    );
};

export default RootLayout;
